# cat /etc/alloyconfig.alloy
logging {
  level  = "info"
  format = "logfmt"
}

prometheus.exporter.unix "local_system" { }

prometheus.scrape "scrape_local_unix_exporter" {
  targets         = prometheus.exporter.unix.local_system.targets
  forward_to      = [prometheus.remote_write.send_metrics.receiver]
  scrape_interval = "15s"
}

prometheus.scrape "epsolar_exporter" {
  targets = [
    {"__address__" = "localhost:8000", "instance" = constants.hostname},
  ]

  forward_to       = [prometheus.remote_write.send_metrics.receiver]

  scrape_interval  = "15s"
  metrics_path     = "/"
}

prometheus.remote_write "send_metrics" {
    endpoint {
        url = "https://prometheus.example.com/api/v1/write"

         basic_auth {
           username = "username"
           password = "password"
         }
    }

    wal {
        max_keepalive_time = "168h"
    }
}
