name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4
    - uses: pre-commit/action@9b88afc9cd57fd75b655d5c71bd38146d07135fe # tag=v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
